### ISSUE TITLE
Undefined subroutine blessed

### ISSUE THREAD

**Issue by mzrinsky** [doy/moosex-nonmoose#5]
For some unknown reason, I started getting the following error ...
{UNKNOWN}: Undefined subroutine &MooseX::NonMoose::Meta::Role::Class::blessed MooseX/NonMoose/Meta/Role/Class.pm line 41

I am using perl v5.14.2 with Moose 2.1005

A quick fix for me was to just add the "use Scalar::Util 'blessed';" line from Moose::Role into MooseX::NonMoose::Meta::Role::Class which did fix the problem.

I have not really dug into this enough to figure out why this started happening, but I assume it started because I recently upgraded most of my modules via. CPAN.
before that I never had any issues.  I looked a little at the past versions of Moose and MooseX::NonMoose on CPAN but did not spot anything obvious (to me) that would have started causing this.

I also installed the latest version of MooseX::NonMoose after having the issue pop up, (I don't remember what version I had installed before that) and all the tests passed, however I still had the above error with the latest version, so I'm not really sure what is going on.

Is this a bug with MooseX::NonMoose?

**Comment by doy** [comment]
`use Moose::Role` should import `blessed`, so I don't see anything immediately wrong with the code in MooseX::NonMoose. Can you give me an example script that's triggering this error?

**Comment by mzrinsky** [comment]
OK, sorry, I'm pretty positive this is not a bug with MooseX::NonMoose.  I tried to write something that would trigger the error but everything works in small scale tests.  As I said, I have been using MooseX::NonMoose for quite a while, with no issues at all, and did not start to have issues until a recent system upgrade, at which time I updated my perl modules.

My actual code is somewhat convoluted, but is basically a DBIx::Class result class, which is using MooseX::NonMoose to extend a base class which is not using Moose.  It has worked fine in the past and so all signs point to my perl modules being botched because of the system upgrade.

The code actually works in my catalyst app, but then when loading the schema from a utility script I use, it fails.  So as I said, I can only guess my perl modules are seriously broken.  Re-installing them cleanly now from CPAN which should fix things I hope.  Either way this is definitely not your problem.  :)

**Comment by mzrinsky** [comment]
Just an FYI (in case anyone ever comes across this, which I kind of doubt), I actually tracked this back to the IO::Prompter module, which is using the Contextual::Return module, which does some crazy things with global caller, and overriding the blessed method.

There is already a bug report about it https://rt.cpan.org/Public/Bug/Display.html?id=26102#txn-306419
